### PR TITLE
Create A frog jumping(1077A)

### PR DESCRIPTION
**Pull request by pavanbsp**
Made it as a basic one

### CODE REVIEW

**Comment by abrahamalbert18** [comment]
Your code looks good. Just a small suggestion: use **else** instead of **elif** since it involves only two conditions. Update and commit it, I'll merge it.

**Comment by pavanbsp** [comment]
Ok sir thank you for your suggestion

**Comment by abrahamalbert18** [comment]
@pavanbsp Thanks for contributing 👍 . I've updated your code and committed the changes to the master branch. Keep contributing, it'll be interesting.

**Comment by pavanbsp** [comment]
@abrahamalbert18 i will definitely contribute my further codes on codeforces and hackerank to your repository
Thank you for merging my code

**Comment by pavanbsp** [comment]
> Ok sir thank you for your suggestion



> Your code looks good. Just a small suggestion: use **else** instead of **elif** since it involves only two conditions. Update and commit it, I'll merge it.

Sorry sir I didn't noticed your update and commit suggestion

**Comment by abrahamalbert18** [comment]
No worries :) All good.

**Pull request merged**
